# Generated by Django 5.0.4 on 2024-05-08 10:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Inventory', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Supplier',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('contact_information', models.TextField()),
                ('lead_time', models.PositiveIntegerField()),
            ],
        ),
        migrations.AddField(
            model_name='component',
            name='cost',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
        ),
        migrations.AddField(
            model_name='component',
            name='unit_of_measure',
            field=models.CharField(default='pcs', max_length=20),
        ),
        migrations.AddField(
            model_name='component',
            name='supplier',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='Inventory.supplier'),
        ),
    ]
