# Generated by Django 5.0.6 on 2024-06-03 15:53

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('Inventory', '0001_initial'),
        ('Manufacturing', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='consumptiontransaction',
            name='material_requisition_item',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Manufacturing.materialrequisitionitem'),
        ),
        migrations.AddField(
            model_name='consumptiontransaction',
            name='user_id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='purchaseorder',
            name='creator',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='purchaserequisition',
            name='component',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Inventory.component'),
        ),
        migrations.AddField(
            model_name='purchaserequisition',
            name='user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='purchaseorder',
            name='purchase_requisition',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Inventory.purchaserequisition'),
        ),
        migrations.AddField(
            model_name='replenishtransaction',
            name='component',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Inventory.component'),
        ),
        migrations.AddField(
            model_name='replenishtransaction',
            name='purchase_requisition',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Inventory.purchaserequisition'),
        ),
        migrations.AddField(
            model_name='replenishtransaction',
            name='user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='purchaseorder',
            name='supplier',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='Inventory.supplier'),
        ),
        migrations.AddField(
            model_name='component',
            name='supplier',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='Inventory.supplier'),
        ),
    ]
