# Generated by Django 5.0.4 on 2024-05-22 13:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Inventory', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='component',
            name='reorder_quantity',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
