# Generated by Django 5.0.6 on 2024-06-13 17:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Inventory', '0003_category_component_category'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='component',
            options={'ordering': ['-updated_at']},
        ),
        migrations.AddField(
            model_name='component',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
