# Generated by Django 5.0.6 on 2024-05-26 10:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Inventory', '0004_alter_purchaserequisition_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='purchaserequisition',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('approved', 'Approved'), ('rejected', 'Rejected'), ('cancelled', 'Cancelled'), ('fulfilled', 'Fulfilled')], default='created', max_length=20),
        ),
    ]
