# Generated by Django 5.0.6 on 2024-05-29 11:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Inventory', '0005_alter_purchaserequisition_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='component',
            name='order_quantity',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
