# Generated by Django 5.0.4 on 2024-05-19 12:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Inventory', '0006_alter_materialrequisition_status_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='consumptiontransaction',
            name='MaterialRequisition',
        ),
        migrations.AddField(
            model_name='consumptiontransaction',
            name='MaterialRequisitionItem',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='Inventory.materialrequisitionitem'),
            preserve_default=False,
        ),
    ]
