# Generated by Django 5.0.6 on 2024-05-31 11:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Inventory', '0006_component_order_quantity'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='purchaserequisition',
            options={'ordering': ['-created_at']},
        ),
    ]
