# Generated by Django 5.0.6 on 2024-06-01 13:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Inventory', '0007_alter_purchaserequisition_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='purchaseorder',
            name='status',
            field=models.CharField(choices=[('draft', 'Draft'), ('open_order', 'Open Order'), ('approved', 'Approved'), ('received', 'Received'), ('invoiced', 'Invoiced'), ('cancelled', 'Cancelled'), ('rejected', 'Rejected')], default='draft', max_length=20),
        ),
    ]
