# Generated by Django 5.0.6 on 2024-06-02 05:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Inventory', '0008_alter_purchaseorder_status'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='purchaseorder',
            name='purchase_manager_approval',
        ),
    ]
