# Generated by Django 5.0.6 on 2024-06-02 07:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Inventory', '0009_remove_purchaseorder_purchase_manager_approval'),
    ]

    operations = [
        migrations.AddField(
            model_name='purchaseorder',
            name='price_per_unit',
            field=models.DecimalField(decimal_places=2, default=100, max_digits=10),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='purchaseorder',
            name='total_price',
            field=models.DecimalField(blank=True, decimal_places=2, default=1000, editable=False, max_digits=10),
            preserve_default=False,
        ),
    ]
