# Generated by Django 5.0.4 on 2024-05-22 10:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Manufacturing', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='manufacturingorder',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('mr_sent', 'MR_Sent'), ('mr_approved', 'MR Approved'), ('mr_rejected', 'MR Rejected'), ('in_production', 'In Production'), ('completed', 'Completed'), ('cancelled', 'Cancelled')], default='pending', max_length=20),
        ),
    ]
