# Generated by Django 5.0.4 on 2024-05-07 14:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Inventory', '0001_initial'),
        ('Manufacturing', '0001_initial'),
        ('Sales', '0006_alter_quotation_status_alter_salesorder_status'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bomitem',
            name='product',
        ),
        migrations.AddField(
            model_name='billofmaterial',
            name='product',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='boms', to='Sales.product'),
        ),
        migrations.AddField(
            model_name='bomitem',
            name='component',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='bom_items', to='Inventory.component'),
        ),
    ]
