# Generated by Django 5.0.4 on 2024-05-24 11:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Manufacturing', '0002_alter_manufacturingorder_status'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='materialrequisition',
            options={'ordering': ['-created_at']},
        ),
    ]
