# Generated by Django 5.0.6 on 2024-06-09 14:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Manufacturing', '0002_manufacturingorder_creater'),
    ]

    operations = [
        migrations.AddField(
            model_name='manufacturingorder',
            name='end_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='manufacturingorder',
            name='estimated_mfg_lead_time',
            field=models.DurationField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='manufacturingorder',
            name='mfg_lead_time',
            field=models.DurationField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='manufacturingorder',
            name='production_lead_time',
            field=models.DurationField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='manufacturingorder',
            name='production_start_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='manufacturingorder',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('mr_sent', 'MR Sent'), ('mr_approved', 'MR Approved'), ('mr_rejected', 'MR Rejected'), ('in_production', 'In Production'), ('completed', 'Completed'), ('cancelled', 'Cancelled')], default='pending', max_length=20),
        ),
    ]
