# Generated by Django 5.0.4 on 2024-05-07 15:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Manufacturing', '0002_remove_bomitem_product_billofmaterial_product_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='billofmaterial',
            name='product',
        ),
    ]
