# Generated by Django 5.0.4 on 2024-05-08 06:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Manufacturing', '0003_remove_billofmaterial_product'),
        ('Sales', '0007_product_bom'),
    ]

    operations = [
        migrations.AddField(
            model_name='billofmaterial',
            name='product',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='boms', to='Sales.product'),
        ),
    ]
