# Generated by Django 5.0.4 on 2024-05-08 10:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Inventory', '0002_supplier_component_cost_component_unit_of_measure_and_more'),
        ('Manufacturing', '0004_billofmaterial_product'),
        ('Sales', '0007_product_bom'),
    ]

    operations = [
        migrations.AddField(
            model_name='manufacturingorder',
            name='bom',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='manufacturing_orders', to='Manufacturing.billofmaterial'),
        ),
        migrations.AddField(
            model_name='manufacturingorder',
            name='product',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='manufacturing_orders', to='Sales.product'),
        ),
        migrations.AddField(
            model_name='manufacturingorder',
            name='quantity',
            field=models.PositiveIntegerField(default=1),
        ),
        migrations.AlterField(
            model_name='billofmaterial',
            name='product',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='boms', to='Sales.product'),
        ),
        migrations.AlterField(
            model_name='bomitem',
            name='component',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='bom_items', to='Inventory.component'),
        ),
    ]
