# Generated by Django 5.0.6 on 2024-06-12 07:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Manufacturing', '0004_rename_product_id_manufacturingorder_product'),
    ]

    operations = [
        migrations.RenameField(
            model_name='manufacturingorder',
            old_name='product',
            new_name='product_id',
        ),
    ]
