# Generated by Django 5.0.4 on 2024-05-08 15:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Inventory', '0002_supplier_component_cost_component_unit_of_measure_and_more'),
        ('Manufacturing', '0005_manufacturingorder_bom_manufacturingorder_product_and_more'),
        ('Sales', '0007_product_bom'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='bomitem',
            options={'verbose_name': 'BOM Item'},
        ),
        migrations.RemoveField(
            model_name='manufacturingorder',
            name='product',
        ),
        migrations.RemoveField(
            model_name='manufacturingorder',
            name='sales_order',
        ),
        migrations.AddField(
            model_name='manufacturingorder',
            name='sales_order_item',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='manufacturing_orders', to='Sales.salesorderitem'),
        ),
        migrations.AddField(
            model_name='materialrequisition',
            name='component',
            field=models.ForeignKey(blank=True, default=1, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='material_requisitions', to='Inventory.component'),
        ),
        migrations.AddField(
            model_name='materialrequisition',
            name='quantity',
            field=models.PositiveIntegerField(default=1),
        ),
        migrations.AlterField(
            model_name='bomitem',
            name='component',
            field=models.ForeignKey(blank=True, default=1, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='bom_items', to='Inventory.component'),
        ),
    ]
