# Generated by Django 5.0.4 on 2024-05-15 04:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Inventory', '0003_alter_supplier_options_supplier_address_and_more'),
        ('Manufacturing', '0007_manufacturingorder_product_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='materialrequisition',
            name='component',
        ),
        migrations.RemoveField(
            model_name='materialrequisition',
            name='quantity',
        ),
        migrations.CreateModel(
            name='MaterialRequisitionItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.PositiveIntegerField()),
                ('component', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='material_requisition_items', to='Inventory.component')),
                ('material_requisition', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='Manufacturing.materialrequisition')),
            ],
        ),
    ]
