# Generated by Django 5.0.4 on 2024-05-18 15:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Manufacturing', '0008_remove_materialrequisition_component_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='manufacturingorder',
            options={'ordering': ['-created_at']},
        ),
    ]
