# Generated by Django 5.0.4 on 2024-05-18 16:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Manufacturing', '0009_alter_manufacturingorder_options'),
        ('Sales', '0008_alter_quotation_options_alter_salesorder_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='billofmaterial',
            name='product',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='bill_of_material', to='Sales.product'),
        ),
    ]
