# Generated by Django 5.0.4 on 2024-05-19 06:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Manufacturing', '0010_alter_billofmaterial_product'),
    ]

    operations = [
        migrations.AddField(
            model_name='materialrequisition',
            name='bom',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='material_requisitions', to='Manufacturing.billofmaterial'),
        ),
    ]
