# Generated by Django 5.0.4 on 2024-05-19 10:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Manufacturing', '0011_materialrequisition_bom'),
    ]

    operations = [
        migrations.AddField(
            model_name='materialrequisition',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('approved', 'Approved'), ('rejected', 'Rejected'), ('fulfilled', 'Fulfilled')], default='pending', max_length=20),
        ),
    ]
