# Generated by Django 5.0.3 on 2024-04-29 15:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Sales', '0003_quotation_remove_salesorder_products_quotationitem_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='quotation',
            name='quotation_number',
        ),
        migrations.RemoveField(
            model_name='quotation',
            name='rfq',
        ),
        migrations.RemoveField(
            model_name='quotationitem',
            name='amount',
        ),
        migrations.AddField(
            model_name='quotation',
            name='customer',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='Sales.customer'),
        ),
    ]
