# Generated by Django 5.0.6 on 2024-06-04 14:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Sales', '0003_product_created_at_product_efficiency_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='weight',
        ),
    ]
