# Generated by Django 5.0.6 on 2024-06-05 09:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Sales', '0004_remove_product_weight'),
    ]

    operations = [
        migrations.AlterField(
            model_name='salesorder',
            name='created_at',
            field=models.DateTimeField(),
        ),
    ]
