# Generated by Django 5.0.4 on 2024-04-30 05:18

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Sales', '0004_remove_quotation_quotation_number_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='quotationitem',
            name='discount_percentage',
        ),
        migrations.RemoveField(
            model_name='quotationitem',
            name='taxes',
        ),
        migrations.AlterField(
            model_name='quotation',
            name='customer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='quotations', to='Sales.customer'),
        ),
    ]
