# Generated by Django 5.0.6 on 2024-06-05 09:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Sales', '0005_alter_salesorder_created_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='salesorder',
            name='updated_at',
            field=models.DateTimeField(),
        ),
    ]
