# Generated by Django 5.0.4 on 2024-05-07 14:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Sales', '0005_remove_quotationitem_discount_percentage_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='quotation',
            name='status',
            field=models.CharField(choices=[('quotation', 'Quotation'), ('quotation_sent', 'Quotation Sent'), ('accepted', 'Accepted'), ('rejected', 'Rejected'), ('cancelled', 'Cancelled'), ('expired', 'Expired')], default='pending', max_length=20),
        ),
        migrations.AlterField(
            model_name='salesorder',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('confirmed', 'Confirmed'), ('processing', 'Processing'), ('in_Production', 'In Production'), ('Ready_for_delivery', 'Ready for delivery'), ('cancelled', 'Cancelled'), ('delivered', 'Delivered')], default='pending', max_length=20),
        ),
    ]
