# Generated by Django 5.0.4 on 2024-05-07 15:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Manufacturing', '0003_remove_billofmaterial_product'),
        ('Sales', '0006_alter_quotation_status_alter_salesorder_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='bom',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='products', to='Manufacturing.billofmaterial'),
        ),
    ]
