# Generated by Django 5.0.6 on 2024-06-13 17:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Sales', '0007_alter_salesorder_created_at_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='customer',
            options={'ordering': ['-created_at']},
        ),
        migrations.AlterModelOptions(
            name='product',
            options={'ordering': ['-created_at']},
        ),
    ]
