# Generated by Django 5.0.4 on 2024-05-18 15:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Sales', '0007_product_bom'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='quotation',
            options={'ordering': ['-created_at']},
        ),
        migrations.AlterModelOptions(
            name='salesorder',
            options={'ordering': ['-created_at']},
        ),
    ]
