# Generated by Django 5.0.6 on 2024-06-13 19:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Sales', '0008_alter_customer_options_alter_product_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='salesorder',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('confirmed', 'Confirmed'), ('processing', 'Processing'), ('in_Production', 'In Production'), ('Ready_for_delivery', 'Ready for delivery'), ('cancelled', 'Cancelled'), ('delivered', 'Delivered')], default='confirmed', max_length=20),
        ),
    ]
