# Generated by Django 5.0.4 on 2024-05-18 16:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Sales', '0008_alter_quotation_options_alter_salesorder_options'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='bom',
        ),
    ]
